// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go
/*
Package model はエージェント・サーバー・フロントで共有するデータ型。
フロントの型は tygo で frontend/src/types/model.ts に生成する(make types)。
*/

/**
 * Sample は 1 区間ぶんのヒストグラム。Slots[i] は [2^i, 2^(i+1)) の件数
 * (slot 0 のみ [0, 2))。単位は Unit。
 */
export interface Sample {
  host: string;
  time: string /* RFC3339 */;
  probe: string;
  unit: string;
  slots: number /* uint64 */[];
  intervalMs: number /* int64 */; // 集計区間の長さ
  cpus: number /* int */; // CPU 使用率の分母に使う
  procs?: ProcStat[];
}
/**
 * ProcStat は 1 区間ぶんのプロセス別集計。同じ名前のプロセスはまとめる。
 * エージェントは待ち時間と CPU 使用の上位だけを送るので、全プロセスではない。
 */
export interface ProcStat {
  comm: string;
  procs: number /* int */; // この名前のプロセス数
  pids: number /* uint32 */[]; // 先頭の数件
  onCpuNs: number /* uint64 */;
  waitCount: number /* uint64 */;
  waitNs: number /* uint64 */;
  waitMaxNs: number /* uint64 */;
  slots: number /* uint64 */[]; // 待ち時間の log2 ヒストグラム(µs)
}
/**
 * HostInfo はサーバーが把握しているホストの一覧に使う。
 */
export interface HostInfo {
  name: string;
  lastSeen: string /* RFC3339 */;
  probes: string[];
}
