// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go
/*
Package model はエージェント・サーバー・フロントで共有するデータ型。
フロントの型は tygo で frontend/src/types/model.ts に生成する(make types)。
*/

/**
 * Sample は 1 区間ぶんのヒストグラム。Slots[i] は [2^i, 2^(i+1)) の件数
 * (slot 0 のみ [0, 2))。単位は Unit。
 */
export interface Sample {
  host: string;
  time: string /* RFC3339 */;
  probe: string;
  unit: string;
  slots: number /* uint64 */[];
  intervalMs: number /* int64 */; // 集計区間の長さ
  cpus: number /* int */; // CPU 使用率の分母に使う
  busyNs: number /* uint64 */; // 全プロセスの CPU 使用時間の合計(eBPF で計測。idle は含まない)
  procs?: ProcStat[];
  mem?: MemStat; // memstall のみ
}
/**
 * MemStat は memstall のサンプルに付けるメモリの状況。
 * StallNs が eBPF の計測値(主役)、使用量と PSI は /proc からの答え合わせ。
 */
export interface MemStat {
  totalBytes: number /* uint64 */;
  availableBytes: number /* uint64 */;
  stallNs: number /* uint64 */; // 区間内に全プロセスが回収で止まった時間の合計(eBPF)
  psiSomeUs: number /* uint64 */; // 区間内の PSI memory some の増分(1 つ以上のタスクが止まっていた時間)
  psiFullUs: number /* uint64 */; // 区間内の PSI memory full の増分(全タスクが止まっていた時間)
}
/**
 * ProcEvent はプロセスの起動・終了・OOM kill の 1 件。
 */
export interface ProcEvent {
  time: string /* RFC3339 */;
  kind: string; // "exec" | "exit" | "oom"
  pid: number /* uint32 */;
  ppid: number /* uint32 */;
  uid: number /* uint32 */;
  comm: string;
  /**
   * exec
   */
  filename?: string;
  /**
   * exit
   */
  exitStatus: number /* int */; // 正常終了時の終了コード
  signal: number /* int */; // シグナルで終了したときのシグナル番号(0 なら正常終了)
  coreDump: boolean;
  lifetimeNs: number /* uint64 */;
  /**
   * oom(Pid/Comm は強制終了されたプロセス)
   */
  triggerPid?: number /* uint32 */;
  triggerComm?: string;
  totalPages?: number /* uint64 */;
  memcg: boolean; // cgroup のメモリ上限による OOM
}
/**
 * EventBatch はエージェントが 1 区間ごとにまとめて送るイベント。
 */
export interface EventBatch {
  host: string;
  time: string /* RFC3339 */;
  events: ProcEvent[];
  dropped: number /* uint64 */; // 溢れて捨てた件数(カーネル側 + エージェント側)
}
/**
 * ProcStat は 1 区間ぶんのプロセス別集計。同じ名前のプロセスはまとめる。
 * エージェントは待ち時間と CPU 使用の上位だけを送るので、全プロセスではない。
 */
export interface ProcStat {
  comm: string;
  procs: number /* int */; // この名前のプロセス数
  pids: number /* uint32 */[]; // 先頭の数件
  onCpuNs: number /* uint64 */;
  waitCount: number /* uint64 */;
  waitNs: number /* uint64 */;
  waitMaxNs: number /* uint64 */;
  slots: number /* uint64 */[]; // 待ち時間の log2 ヒストグラム(µs)
  /**
   * memstall のみ。memstall では Wait* を「メモリ回収で止まった」の意味で使う
   */
  reclaimedPages?: number /* uint64 */;
  memcgCount?: number /* uint64 */; // うち cgroup の上限による回収の回数
}
/**
 * HostInfo はサーバーが把握しているホストの一覧に使う。
 */
export interface HostInfo {
  name: string;
  lastSeen: string /* RFC3339 */;
  probes: string[];
}
