// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go
/*
Package model はエージェント・サーバー・フロントで共有するデータ型。
フロントの型は tygo で frontend/src/types/model.ts に生成する(make types)。
*/

/**
 * Sample は 1 区間ぶんのヒストグラム。Slots[i] は [2^i, 2^(i+1)) の件数
 * (slot 0 のみ [0, 2))。単位は Unit。
 */
export interface Sample {
  host: string;
  time: string /* RFC3339 */;
  probe: string;
  unit: string;
  slots: number /* uint64 */[];
}
/**
 * HostInfo はサーバーが把握しているホストの一覧に使う。
 */
export interface HostInfo {
  name: string;
  lastSeen: string /* RFC3339 */;
  probes: string[];
}
